altschool_final_project:
  outputs:
    dev:
      dataset: transformed
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/Awalem/Desktop/alt-school-project-425214-bc2c66d916c1.json
      location: europe-west1
      method: service-account
      priority: interactive
      project: alt-school-project-425214
      threads: 1
      type: bigquery
  target: dev
